version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hoa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hoa_admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d hoa_db -U hoa_admin"]
      timeout: 10s
      interval: 5s
      retries: 10

volumes:
  db_data: